USE DATABASE My_DB;
CREATE SCHEMA RAW_DATA_TOYS;


-- Create the Sales table automatically based on the files in the /sales/ folder
CREATE OR REPLACE FILE FORMAT MY_CSV_FORMAT
    TYPE = CSV
    FIELD_DELIMITER = ','
    SKIP_HEADER = 1
    NULL_IF = ('NULL', 'null')
    EMPTY_FIELD_AS_NULL = TRUE;

-- Check Data
LIST @"TOYS_DB"."RAW_DATA_TOYS"."SALES_STAGED";

-- Load the sales file

CREATE OR REPLACE TABLE "TOYS_DB"."RAW_DATA_TOYS"."STG_SALES" (
    C1 STRING, C2 STRING, C3 STRING, C4 STRING, C5 STRING);

COPY INTO "TOYS_DB"."RAW_DATA_TOYS"."STG_SALES"
FROM @"TOYS_DB"."RAW_DATA_TOYS"."SALES_STAGED"/sales.csv
FILE_FORMAT = (
    TYPE = CSV
    FIELD_DELIMITER = ','
    SKIP_HEADER = 1
    RECORD_DELIMITER = '\n'  -- Explicitly set the line break
    ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE
)
FORCE = TRUE;

SELECT count(*) FROM "TOYS_DB"."RAW_DATA_TOYS"."STG_SALES";

--Load inventory
CREATE OR REPLACE TABLE "TOYS_DB"."RAW_DATA_TOYS"."STG_INVENTORY" (
    C1 STRING, C2 STRING, C3 STRING);

COPY INTO "TOYS_DB"."RAW_DATA_TOYS"."STG_INVENTORY"
FROM @"TOYS_DB"."RAW_DATA_TOYS"."INVENTORY_STAGED"/inventory.csv
FILE_FORMAT = (
    TYPE = CSV
    FIELD_DELIMITER = ','
    SKIP_HEADER = 1
    RECORD_DELIMITER = '\n'  
    ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE
)
FORCE = TRUE;

-- Load Products
CREATE OR REPLACE TABLE "TOYS_DB"."RAW_DATA_TOYS"."STG_PRODUCTS" (
    C1 STRING, C2 STRING, C3 STRING, C4 STRING, C5 STRING);

COPY INTO "TOYS_DB"."RAW_DATA_TOYS"."STG_PRODUCTS"
FROM @"TOYS_DB"."RAW_DATA_TOYS"."PRODUCTS_DATA_STAGED"/products.csv
FILE_FORMAT = (
    TYPE = CSV
    FIELD_DELIMITER = ','
    SKIP_HEADER = 1
    RECORD_DELIMITER = '\n'  
    ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE
)
FORCE = TRUE;

-- Load stores
CREATE OR REPLACE TABLE "TOYS_DB"."RAW_DATA_TOYS"."STG_STORES" (
    C1 STRING, C2 STRING, C3 STRING, C4 STRING, C5 STRING);

COPY INTO "TOYS_DB"."RAW_DATA_TOYS"."STG_STORES"
FROM @"TOYS_DB"."RAW_DATA_TOYS"."STORES_STAGED"/stores.csv
FILE_FORMAT = (
    TYPE = CSV
    FIELD_DELIMITER = ','
    SKIP_HEADER = 1
    RECORD_DELIMITER = '\n'  
    ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE
)
FORCE = TRUE;

-- Renaming the column headers

ALTER TABLE "TOYS_DB"."RAW_DATA_TOYS"."STG_SALES" RENAME COLUMN C1 TO SALE_ID;
ALTER TABLE "TOYS_DB"."RAW_DATA_TOYS"."STG_SALES" RENAME COLUMN C2 TO DATE;
ALTER TABLE "TOYS_DB"."RAW_DATA_TOYS"."STG_SALES" RENAME COLUMN C3 TO STORE_ID;
ALTER TABLE "TOYS_DB"."RAW_DATA_TOYS"."STG_SALES" RENAME COLUMN C4 TO PRODUCT_ID;
ALTER TABLE "TOYS_DB"."RAW_DATA_TOYS"."STG_SALES" RENAME COLUMN C5 TO UNITS;

ALTER TABLE "TOYS_DB"."RAW_DATA_TOYS"."STG_PRODUCTS" RENAME COLUMN C1 TO PRODUCT_ID;
ALTER TABLE "TOYS_DB"."RAW_DATA_TOYS"."STG_PRODUCTS" RENAME COLUMN C2 TO PRODUCT_NAME;
ALTER TABLE "TOYS_DB"."RAW_DATA_TOYS"."STG_PRODUCTS" RENAME COLUMN C3 TO PRODUCT_CATEGORY;
ALTER TABLE "TOYS_DB"."RAW_DATA_TOYS"."STG_PRODUCTS" RENAME COLUMN C4 TO PRODUCT_COST;
ALTER TABLE "TOYS_DB"."RAW_DATA_TOYS"."STG_PRODUCTS" RENAME COLUMN C5 TO PRODUCT_PRICE;

SELECT * FROM "TOYS_DB"."RAW_DATA_TOYS"."STG_SALES" LIMIT 5;

