use database toys_db;

SELECT 
    COUNT(*) as TOTAL_SALES_RECORDS,
    SUM(UNITS_SOLD) as UNITS_SOLD,
    SUM(TOTAL_REVENUE) as TOTAL_REVENUE,
    MIN(SALE_DATE) as START_DATE,
    MAX(SALE_DATE) as END_DATE
FROM "TOYS_DB"."RAW_DATA_TOYS"."V_SALES_PERFORMANCE";


-- Check Trends 
SELECT 
    SALE_DATE, 
    SUM(TOTAL_REVENUE) as DAILY_REVENUE,
    AVG(SUM(TOTAL_REVENUE)) OVER (ORDER BY SALE_DATE ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) as MOVING_AVG_7D
FROM "TOYS_DB"."RAW_DATA_TOYS"."V_SALES_PERFORMANCE"
GROUP BY 1
ORDER BY 1;


-- Pareto Analysis

SELECT 
    PRODUCT_CATEGORY, 
    SUM(TOTAL_REVENUE) as REVENUE,
    ROUND(REVENUE / SUM(REVENUE) OVER () * 100, 2) as PERCENT_OF_TOTAL
FROM "TOYS_DB"."RAW_DATA_TOYS"."V_SALES_PERFORMANCE"
GROUP BY 1
ORDER BY REVENUE DESC;


-- when to reorder
SELECT 
    PRODUCT_NAME,
    AVG(UNITS_SOLD) as AVG_DAILY_SALES,
    (AVG_DAILY_SALES * 14) as REORDER_LEVEL -- Assuming 14-day delivery lead time
FROM TOYS_DB.RAW_DATA_TOYS.V_SALES_PERFORMANCE
GROUP BY 1;



